### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by amirkhan81** [mapbox/poi-by-radius-demo#1]
I'm having trouble building this on any of our machines, all with Node and NPM installed, log below. Any insight as to what's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart poi-by-radius-demo@0.0.0
6 info start poi-by-radius-demo@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info poi-by-radius-demo@0.0.0 Failed to exec start script
9 verbose stack Error: poi-by-radius-demo@0.0.0 start: `budo index.js --serve=bundle.js --live -d`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid poi-by-radius-demo@0.0.0
11 verbose cwd /Users/blackswan2/Downloads/poi-by-radius-demo-mb-pages
12 error Darwin 15.2.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error poi-by-radius-demo@0.0.0 start: `budo index.js --serve=bundle.js --live -d`
20 error spawn ENOENT
21 error Failed at the poi-by-radius-demo@0.0.0 start script 'budo index.js --serve=bundle.js --live -d'.
21 error This is most likely a problem with the poi-by-radius-demo package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     budo index.js --serve=bundle.js --live -d
21 error You can get their info via:
21 error     npm owner ls poi-by-radius-demo
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by lyzidiamond** [comment]
Hi @amirkhan81! Run `npm install` before you run `npm start && open http://localhost:9966/` to install the dependencies. After that, it should work!

**Comment by amirkhan81** [comment]
Ahhhhh! Thank you!!
-- 

Amir Khan
Black Swan Interactive 

1802 Perrysburg Holland Rd
Holland, Ohio 43528 USA

t:   +1.567.343.2255 <tel:%2B1.567.343.2255>  
m: +1.614.354.8672 <tel:%2B1.614.354.8672> 
e: amir@blackswaninteractive.com <http://amir@blackswaninteractive.com/>
