### ISSUE TITLE
missing access token

### ISSUE THREAD

**Issue by katydecorah** [mapbox/poi-by-radius-demo#5]
@tristen I'm guessing a casualty to the token rotation

![image](https://cloud.githubusercontent.com/assets/2180540/12732886/a48720f8-c905-11e5-86cb-f7ac89d957c9.png)

**Comment by tristen** [comment]
Yikes - good catch. Should be fixed up https://www.mapbox.com/poi-by-radius-demo/#14/40.7268/-74.0015
