### ISSUE TITLE
code already minified?

### ISSUE THREAD

**Issue by musicformellons** [mapbox/poi-by-radius-demo#6]
I like your demo. I am familiar with these examples:
https://www.mapbox.com/mapbox-gl-js/examples/

I am a bit puzzled though where the code is for:
1) the radius circle
2) the 'info panel'
3) style of the map

I don't really find these, are these already bundled in bundle.js. Maybe you could help?

**Comment by tristen** [comment]
Hi @musicformellons the source code is located in [index.js](https://github.com/mapbox/poi-by-radius-demo/blob/mb-pages/index.js) with some of the [scripts required in](https://github.com/mapbox/poi-by-radius-demo/blob/16c919661893136d4e9d35c902e8f8279e959d33/index.js#L6-L22) using the help of [Browserify](https://www.npmjs.com/package/browserify). Any external libs are cited in [package.json](https://github.com/mapbox/poi-by-radius-demo/blob/mb-pages/package.json) and installation instructions are here: https://github.com/mapbox/poi-by-radius-demo#running-locally.

Hope this helps!

**Comment by musicformellons** [comment]
Yeah, it is in index.js; thanks!

**Comment by tristen** [comment]
:+1:
